"""Build data/raw/billboard_2016_2025.csv from per-year Billboard Year-End Hot 100 lists.

The 2016-2019 rows are the original curated top-25 (they land in the 2010s decade,
already well populated from walkerkq). The 2020-2025 rows are expanded toward the
full Year-End Hot 100 (~100/year) so the 2020s sample is comparable to other decades.

Entries are (artist, title, rank). `artist` is the LEAD artist only and `title` is the
clean track name (no "feat.") so the lrclib artist+track lookup matches. Songs that
chart in two years appear in both; dedup on lowercased artist|title happens downstream
in scraper_v2.merge_and_save.
"""
import csv
import os

# year -> list of (artist, title, year-end rank)
YEARS: dict[int, list[tuple[str, str, int]]] = {
    2016: [
        ("Justin Bieber", "Love Yourself", 1),
        ("Drake", "One Dance", 2),
        ("Rihanna", "Work", 3),
        ("Justin Bieber", "Sorry", 4),
        ("The Chainsmokers", "Don't Let Me Down", 5),
        ("Desiigner", "Panda", 6),
        ("Lukas Graham", "7 Years", 7),
        ("Sia", "Cheap Thrills", 8),
        ("Fifth Harmony", "Work from Home", 9),
        ("Calvin Harris", "This Is What You Came For", 10),
        ("Mike Posner", "I Took a Pill in Ibiza", 11),
        ("The Chainsmokers", "Closer", 12),
        ("Twenty One Pilots", "Stressed Out", 13),
        ("Twenty One Pilots", "Heathens", 14),
        ("Adele", "Hello", 15),
        ("Flo Rida", "My House", 16),
        ("DJ Snake", "Let Me Love You", 17),
        ("Zayn", "Pillowtalk", 18),
        ("Meghan Trainor", "Me Too", 19),
        ("Charlie Puth", "One Call Away", 20),
        ("Selena Gomez", "Hands to Myself", 21),
        ("Drake", "Hotline Bling", 22),
        ("Beyonce", "Formation", 23),
        ("Bruno Mars", "24K Magic", 24),
        ("Justin Timberlake", "Can't Stop the Feeling", 25),
    ],
    2017: [
        ("Ed Sheeran", "Shape of You", 1),
        ("Luis Fonsi", "Despacito", 2),
        ("Bruno Mars", "That's What I Like", 3),
        ("The Chainsmokers", "Something Just Like This", 4),
        ("DJ Khaled", "I'm the One", 5),
        ("Migos", "Bad and Boujee", 6),
        ("Kendrick Lamar", "HUMBLE.", 7),
        ("Post Malone", "Congratulations", 8),
        ("Sam Hunt", "Body Like a Back Road", 9),
        ("Imagine Dragons", "Believer", 10),
        ("Charlie Puth", "Attention", 11),
        ("Camila Cabello", "Havana", 12),
        ("Taylor Swift", "Look What You Made Me Do", 13),
        ("Future", "Mask Off", 14),
        ("Ed Sheeran", "Perfect", 15),
        ("Khalid", "Location", 16),
        ("Cardi B", "Bodak Yellow", 17),
        ("French Montana", "Unforgettable", 18),
        ("Maroon 5", "What Lovers Do", 19),
        ("Logic", "1-800-273-8255", 20),
        ("Post Malone", "Rockstar", 21),
        ("Selena Gomez", "It Ain't Me", 22),
        ("Lil Uzi Vert", "XO Tour Llif3", 23),
        ("DJ Khaled", "Wild Thoughts", 24),
        ("Zedd", "Stay", 25),
    ],
    2018: [
        ("Drake", "God's Plan", 1),
        ("Post Malone", "Psycho", 2),
        ("Post Malone", "Better Now", 3),
        ("Cardi B", "I Like It", 4),
        ("Bruno Mars", "Finesse", 5),
        ("Drake", "Nice for What", 6),
        ("Camila Cabello", "Never Be the Same", 7),
        ("Ariana Grande", "No Tears Left to Cry", 8),
        ("Maroon 5", "Girls Like You", 9),
        ("Childish Gambino", "This Is America", 10),
        ("Drake", "In My Feelings", 11),
        ("Travis Scott", "Sicko Mode", 12),
        ("XXXTentacion", "SAD!", 13),
        ("Bebe Rexha", "Meant to Be", 14),
        ("Marshmello", "Happier", 15),
        ("Lady Gaga", "Shallow", 16),
        ("5 Seconds of Summer", "Youngblood", 17),
        ("Post Malone", "Sunflower", 18),
        ("Ariana Grande", "Thank U, Next", 19),
        ("Imagine Dragons", "Natural", 20),
        ("Tyga", "Taste", 21),
        ("Halsey", "Without Me", 22),
        ("Juice WRLD", "Lucid Dreams", 23),
        ("Ella Mai", "Boo'd Up", 24),
        ("Khalid", "Love Lies", 25),
    ],
    2019: [
        ("Lil Nas X", "Old Town Road", 1),
        ("Billie Eilish", "Bad Guy", 2),
        ("Post Malone", "Sunflower", 3),
        ("Halsey", "Without Me", 4),
        ("Shawn Mendes", "Senorita", 5),
        ("Lil Tecca", "Ran$om", 6),
        ("Khalid", "Talk", 7),
        ("Lewis Capaldi", "Someone You Loved", 8),
        ("Jonas Brothers", "Sucker", 9),
        ("Ariana Grande", "7 Rings", 10),
        ("Post Malone", "Wow.", 11),
        ("Ed Sheeran", "I Don't Care", 12),
        ("Sam Smith", "Dancing with a Stranger", 13),
        ("Taylor Swift", "ME!", 14),
        ("Ava Max", "Sweet but Psycho", 15),
        ("Lizzo", "Truth Hurts", 16),
        ("Travis Scott", "Highest in the Room", 17),
        ("Marshmello", "Wow", 18),
        ("Maroon 5", "Memories", 19),
        ("Billie Eilish", "When the Party's Over", 20),
        ("Cardi B", "Please Me", 21),
        ("DaBaby", "Suge", 22),
        ("Lil Nas X", "Panini", 23),
        ("Lauv", "I Like Me Better", 24),
        ("Y2K", "Lalala", 25),
    ],
    2020: [
        ("The Weeknd", "Blinding Lights", 1),
        ("Post Malone", "Circles", 2),
        ("Roddy Ricch", "The Box", 3),
        ("Dua Lipa", "Don't Start Now", 4),
        ("DaBaby", "Rockstar", 5),
        ("Harry Styles", "Adore You", 6),
        ("Future", "Life Is Good", 7),
        ("Maroon 5", "Memories", 8),
        ("Maren Morris", "The Bones", 9),
        ("Lewis Capaldi", "Someone You Loved", 10),
        ("Megan Thee Stallion", "Savage", 11),
        ("Trevor Daniel", "Falling", 12),
        ("Harry Styles", "Watermelon Sugar", 13),
        ("Justin Bieber", "Intentions", 14),
        ("Mustard", "Ballin'", 15),
        ("Doja Cat", "Say So", 16),
        ("Jack Harlow", "Whats Poppin", 17),
        ("Surfaces", "Sunday Best", 18),
        ("SAINt JHN", "Roses", 19),
        ("Drake", "Toosie Slide", 20),
        ("Lewis Capaldi", "Before You Go", 21),
        ("Tones and I", "Dance Monkey", 22),
        ("Arizona Zervas", "Roxanne", 23),
        ("Justin Bieber", "Yummy", 24),
        ("Lady Gaga", "Rain on Me", 25),
        ("Powfu", "Death Bed", 26),
        ("Billie Eilish", "Everything I Wanted", 27),
        ("The Weeknd", "Heartless", 28),
        ("Blackbear", "Hot Girl Bummer", 29),
        ("Selena Gomez", "Lose You to Love Me", 30),
        ("Cardi B", "WAP", 31),
        ("24kGoldn", "Mood", 32),
        ("Kane Brown", "Be Like That", 33),
        ("Luke Combs", "Lovin' on You", 34),
        ("Jawsh 685", "Savage Love", 35),
        ("BTS", "Dynamite", 36),
        ("Justin Bieber", "Holy", 37),
        ("Drake", "Laugh Now Cry Later", 38),
        ("Chris Brown", "Go Crazy", 39),
        ("Dua Lipa", "Break My Heart", 40),
        ("Pop Smoke", "What You Know Bout Love", 41),
        ("Gabby Barrett", "I Hope", 42),
        ("Dan + Shay", "10,000 Hours", 43),
        ("Lil Baby", "We Paid", 44),
        ("Doja Cat", "Like That", 45),
        ("DaBaby", "Bop", 46),
        ("Roddy Ricch", "High Fashion", 47),
        ("Lil Mosey", "Blueberry Faygo", 48),
        ("Black Eyed Peas", "Ritmo", 49),
        ("Post Malone", "Wow", 50),
        ("Lil Baby", "Emotionally Scarred", 51),
        ("Ariana Grande", "Positions", 52),
        ("StaySolidRocky", "Party Girl", 53),
        ("Internet Money", "Lemonade", 54),
        ("Future", "Hard to Choose One", 55),
        ("Pop Smoke", "For the Night", 56),
        ("Lil Uzi Vert", "Futsal Shuffle 2020", 57),
        ("Megan Thee Stallion", "Captain Hook", 58),
        ("Conan Gray", "Heather", 59),
        ("Bad Bunny", "Dakiti", 60),
        ("Shawn Mendes", "Senorita", 61),
        ("Lil Durk", "Viral Moment", 62),
        ("Polo G", "Go Stupid", 63),
        ("Jack Harlow", "Tyler Herro", 64),
        ("Drake", "Chicago Freestyle", 65),
        ("Ariana Grande", "Rain on Me", 66),
        ("Doja Cat", "Streets", 67),
        ("Miley Cyrus", "Midnight Sky", 68),
        ("Taylor Swift", "Cardigan", 69),
        ("Lewis Capaldi", "Hold Me While You Wait", 70),
        ("BENEE", "Supalonely", 71),
        ("Roddy Ricch", "Please Excuse Me for Being Antisocial", 72),
        ("Juice WRLD", "Come and Go", 73),
        ("Pop Smoke", "Mood Swings", 74),
        ("Gunna", "Dollaz on My Head", 75),
        ("Megan Thee Stallion", "Girls in the Hood", 76),
        ("Joel Corry", "Lonely", 77),
        ("Sam Smith", "Dancing with a Stranger", 78),
        ("Topic", "Breaking Me", 79),
        ("Lil Tjay", "20/20", 80),
        ("KAROL G", "Tusa", 81),
        ("Eminem", "Godzilla", 82),
        ("Taylor Swift", "Willow", 83),
        ("The Weeknd", "In Your Eyes", 84),
        ("Halsey", "You Should Be Sad", 85),
        ("Dua Lipa", "Physical", 86),
        ("Megan Thee Stallion", "B.I.T.C.H.", 87),
        ("Future", "Life Is Good Remix", 88),
        ("Saweetie", "Tap In", 89),
        ("Young Thug", "The London", 90),
    ],
    2021: [
        ("Dua Lipa", "Levitating", 1),
        ("Olivia Rodrigo", "Drivers License", 2),
        ("The Weeknd", "Save Your Tears", 3),
        ("The Kid Laroi", "Stay", 4),
        ("Olivia Rodrigo", "Good 4 U", 5),
        ("Doja Cat", "Kiss Me More", 6),
        ("Silk Sonic", "Leave the Door Open", 7),
        ("Cardi B", "Up", 8),
        ("Lil Nas X", "Montero", 9),
        ("Glass Animals", "Heat Waves", 10),
        ("Olivia Rodrigo", "Deja Vu", 11),
        ("Justin Bieber", "Peaches", 12),
        ("Polo G", "Rapstar", 13),
        ("BTS", "Butter", 14),
        ("Lil Nas X", "Industry Baby", 15),
        ("Doja Cat", "Need to Know", 16),
        ("Dua Lipa", "Don't Start Now", 17),
        ("Masked Wolf", "Astronaut in the Ocean", 18),
        ("Lil Tjay", "Calling My Phone", 19),
        ("24kGoldn", "Mood", 20),
        ("The Weeknd", "Blinding Lights", 21),
        ("Olivia Rodrigo", "Traitor", 22),
        ("Ed Sheeran", "Bad Habits", 23),
        ("Walker Hayes", "Fancy Like", 24),
        ("Bruno Mars", "Leave the Door Open", 25),
        ("Drake", "Way 2 Sexy", 26),
        ("Olivia Rodrigo", "Brutal", 27),
        ("Doja Cat", "Woman", 28),
        ("The Weeknd", "Save Your Tears Remix", 29),
        ("Justin Bieber", "Stay", 30),
        ("Giveon", "Heartbreak Anniversary", 31),
        ("Drake", "Knife Talk", 32),
        ("Pooh Shiesty", "Back in Blood", 33),
        ("Lil Nas X", "Sun Goes Down", 34),
        ("Maroon 5", "Beautiful Mistakes", 35),
        ("Chris Brown", "Go Crazy", 36),
        ("SZA", "Good Days", 37),
        ("Doja Cat", "You Right", 38),
        ("Cardi B", "WAP", 39),
        ("Drake", "Laugh Now Cry Later", 40),
        ("J. Cole", "My Life", 41),
        ("Migos", "Straightenin", 42),
        ("Moneybagg Yo", "Wockesha", 43),
        ("Tyler the Creator", "Wusyaname", 44),
        ("Coldplay", "My Universe", 45),
        ("Adele", "Easy on Me", 46),
        ("Ariana Grande", "Positions", 47),
        ("The Weeknd", "Take My Breath", 48),
        ("Lil Durk", "Laugh Now Cry Later", 49),
        ("Kali Uchis", "Telepatia", 50),
        ("Tate McRae", "You Broke Me First", 51),
        ("Pop Smoke", "What You Know Bout Love", 52),
        ("Megan Thee Stallion", "Body", 53),
        ("Rod Wave", "Tombstone", 54),
        ("Roddy Ricch", "Late at Night", 55),
        ("Drake", "Girls Want Girls", 56),
        ("Drake", "Fair Trade", 57),
        ("Saweetie", "Best Friend", 58),
        ("Justin Bieber", "Holy", 59),
        ("Doja Cat", "Streets", 60),
        ("Lil Baby", "On Me", 61),
        ("Ariana Grande", "34+35", 62),
        ("Jason Derulo", "Take You Dancing", 63),
        ("DJ Khaled", "Every Chance I Get", 64),
        ("Lil Tjay", "Headshot", 65),
        ("Young Stoner Life", "Solid", 66),
        ("Russ", "Take You Dancing", 67),
        ("Internet Money", "His & Hers", 68),
        ("Tiesto", "The Business", 69),
        ("Migos", "Type Shit", 70),
        ("Gera MX", "Botella Tras Botella", 71),
        ("Olivia Rodrigo", "Happier", 72),
        ("Bo Burnham", "All Eyes on Me", 73),
        ("Toosii", "What It Cost", 74),
        ("Lil Durk", "Finesse Out the Gang Way", 75),
        ("Dua Lipa", "We're Good", 76),
        ("Polo G", "Gang Gang", 77),
        ("Kanye West", "Hurricane", 78),
        ("Rauw Alejandro", "Todo de Ti", 79),
        ("CKay", "Love Nwantiti", 80),
        ("Elton John", "Cold Heart", 81),
        ("Ed Sheeran", "Shivers", 82),
        ("The Weeknd", "Out of Time", 83),
        ("Doja Cat", "Get into It", 84),
        ("Nardo Wick", "Who Want Smoke", 85),
        ("Kacey Musgraves", "Justified", 86),
        ("Yung Bleu", "You're Mines Still", 87),
        ("Luke Combs", "Forever After All", 88),
        ("Chris Stapleton", "Starting Over", 89),
        ("Bad Bunny", "Dakiti", 90),
    ],
    2022: [
        ("Harry Styles", "As It Was", 1),
        ("Glass Animals", "Heat Waves", 2),
        ("Jack Harlow", "First Class", 3),
        ("Future", "Wait for U", 4),
        ("Lizzo", "About Damn Time", 5),
        ("Kate Bush", "Running Up That Hill", 6),
        ("Bad Bunny", "Me Porto Bonito", 7),
        ("Steve Lacy", "Bad Habit", 8),
        ("Sam Smith", "Unholy", 9),
        ("Taylor Swift", "Anti-Hero", 10),
        ("Bad Bunny", "Titi Me Pregunto", 11),
        ("Beyonce", "Break My Soul", 12),
        ("The Kid Laroi", "Stay", 13),
        ("Nicky Youre", "Sunroof", 14),
        ("Em Beihold", "Numb Little Bug", 15),
        ("Lil Nas X", "Industry Baby", 16),
        ("Gunna", "Pushin P", 17),
        ("Jack Harlow", "Industry Baby", 18),
        ("Doja Cat", "Vegas", 19),
        ("Nicki Minaj", "Super Freaky Girl", 20),
        ("Latto", "Big Energy", 21),
        ("Post Malone", "I Like You", 22),
        ("OneRepublic", "I Ain't Worried", 23),
        ("Drake", "Jimmy Cooks", 24),
        ("Imagine Dragons", "Enemy", 25),
        ("Charlie Puth", "Light Switch", 26),
        ("Future", "Puffin on Zootiez", 27),
        ("Encanto Cast", "We Don't Talk About Bruno", 28),
        ("Megan Thee Stallion", "Sweetest Pie", 29),
        ("Bad Bunny", "Moscow Mule", 30),
        ("Adele", "Easy on Me", 31),
        ("Elton John", "Cold Heart", 32),
        ("GAYLE", "abcdefu", 33),
        ("The Weeknd", "Out of Time", 34),
        ("Morgan Wallen", "Wasted on You", 35),
        ("Cody Johnson", "Til You Can't", 36),
        ("Lainey Wilson", "Heart Like a Truck", 37),
        ("Zach Bryan", "Something in the Orange", 38),
        ("Luke Combs", "The Kind of Love We Make", 39),
        ("Carrie Underwood", "Ghost Story", 40),
        ("DJ Khaled", "Staying Alive", 41),
        ("Future", "I Never Liked You", 42),
        ("Kendrick Lamar", "N95", 43),
        ("Jack Harlow", "Churchill Downs", 44),
        ("Lil Baby", "In a Minute", 45),
        ("Roddy Ricch", "The Box", 46),
        ("Megan Thee Stallion", "Plan B", 47),
        ("Lizzo", "2 Be Loved", 48),
        ("Doja Cat", "Woman", 49),
        ("Harry Styles", "Late Night Talking", 50),
        ("Lauv", "26", 51),
        ("Camila Cabello", "Bam Bam", 52),
        ("Rosa Linn", "Snap", 53),
        ("Joji", "Glimpse of Us", 54),
        ("Beyonce", "Cuff It", 55),
        ("Future", "Massaging Me", 56),
        ("Drake", "Sticky", 57),
        ("Tion Wayne", "Body", 58),
        ("Muni Long", "Hrs and Hrs", 59),
        ("Tems", "Free Mind", 60),
        ("Frank Ocean", "Lost", 61),
        ("Yung Gravy", "Betty", 62),
        ("Babytron", "Emperor of the Universe", 63),
        ("DripReport", "Skechers", 64),
        ("ScHoolboy Q", "THat Part", 65),
        ("Quavo", "Hotel Lobby", 66),
        ("Burna Boy", "Last Last", 67),
        ("Stephen Sanchez", "Until I Found You", 68),
        ("Steve Lacy", "Static", 69),
        ("Lizzo", "Grrrls", 70),
        ("The Weeknd", "Sacrifice", 71),
        ("Future", "Keep It Burnin", 72),
        ("Kendrick Lamar", "Die Hard", 73),
        ("Megan Thee Stallion", "Her", 74),
        ("Bad Bunny", "Efecto", 75),
        ("Rauw Alejandro", "Desesperados", 76),
        ("Anitta", "Envolver", 77),
        ("Chris Brown", "Under the Influence", 78),
        ("PinkPantheress", "Just for Me", 79),
        ("Coi Leray", "Players", 80),
        ("Nardo Wick", "Who Want Smoke", 81),
        ("Hitkidd", "Shabooya", 82),
        ("GloRilla", "F.N.F.", 83),
        ("Kodak Black", "Super Gremlin", 84),
        ("Gunna", "Banking on Me", 85),
        ("Lil Durk", "Broadway Girls", 86),
        ("Polo G", "Distraction", 87),
        ("Future", "712PM", 88),
        ("Mary J. Blige", "Good Morning Gorgeous", 89),
        ("Cigarettes After Sex", "Apocalypse", 90),
    ],
    2023: [
        ("Morgan Wallen", "Last Night", 1),
        ("Miley Cyrus", "Flowers", 2),
        ("Taylor Swift", "Anti-Hero", 3),
        ("SZA", "Kill Bill", 4),
        ("Jung Kook", "Seven", 5),
        ("Rema", "Calm Down", 6),
        ("Doja Cat", "Paint the Town Red", 7),
        ("Taylor Swift", "Cruel Summer", 8),
        ("Olivia Rodrigo", "Vampire", 9),
        ("Eslabon Armado", "Ella Baila Sola", 10),
        ("Luke Combs", "Fast Car", 11),
        ("Dua Lipa", "Dance the Night", 12),
        ("Metro Boomin", "Creepin'", 13),
        ("Taylor Swift", "Karma", 14),
        ("SZA", "Snooze", 15),
        ("Rema", "Calm Down Remix", 16),
        ("Toosii", "Favorite Song", 17),
        ("Drake", "Rich Flex", 18),
        ("Peso Pluma", "Ella Baila Sola", 19),
        ("Zach Bryan", "Something in the Orange", 20),
        ("Olivia Rodrigo", "Get Him Back", 21),
        ("Yng Lvcas", "La Bebe", 22),
        ("Gunna", "Fukumean", 23),
        ("Tyla", "Water", 24),
        ("Lil Durk", "All My Life", 25),
        ("David Kushner", "Daylight", 26),
        ("Jimin", "Like Crazy", 27),
        ("Lil Uzi Vert", "Just Wanna Rock", 28),
        ("PinkPantheress", "Boy's a Liar", 29),
        ("Doja Cat", "Agora Hills", 30),
        ("Bizarrap", "Shakira BZRP Music Sessions 53", 31),
        ("Morgan Wallen", "You Proof", 32),
        ("Morgan Wallen", "Thinkin Bout Me", 33),
        ("Taylor Swift", "Snow on the Beach", 34),
        ("Bad Bunny", "Where She Goes", 35),
        ("Karol G", "TQG", 36),
        ("Peso Pluma", "Lady Gaga", 37),
        ("Drake", "Search & Rescue", 38),
        ("Travis Scott", "Meltdown", 39),
        ("Doja Cat", "Attention", 40),
        ("Nicki Minaj", "Barbie World", 41),
        ("Dua Lipa", "Houdini", 42),
        ("Jelly Roll", "Need a Favor", 43),
        ("Chris Stapleton", "White Horse", 44),
        ("Morgan Wallen", "One Thing at a Time", 45),
        ("Bailey Zimmerman", "Rock and a Hard Place", 46),
        ("HARDY", "Wait in the Truck", 47),
        ("Oliver Anthony", "Rich Men North of Richmond", 48),
        ("Zach Bryan", "I Remember Everything", 49),
        ("Doechii", "What It Is", 50),
        ("Coi Leray", "Players", 51),
        ("Kaliii", "Area Codes", 52),
        ("NLE Choppa", "Slut Me Out", 53),
        ("Lil Durk", "Stand by Me", 54),
        ("Metro Boomin", "Superhero", 55),
        ("The Weeknd", "Creepin", 56),
        ("Lana Del Rey", "Say Yes to Heaven", 57),
        ("Travis Scott", "FE!N", 58),
        ("Drake", "Slime You Out", 59),
        ("Olivia Rodrigo", "Bad Idea Right", 60),
        ("Fifty Fifty", "Cupid", 61),
        ("Taylor Swift", "Is It Over Now", 62),
        ("SZA", "Low", 63),
        ("21 Savage", "Redrum", 64),
        ("Sped Up Nightcore", "Sped Up", 65),
        ("Tate McRae", "Greedy", 66),
        ("Doja Cat", "Demons", 67),
        ("Post Malone", "Mourning", 68),
        ("Ed Sheeran", "Eyes Closed", 69),
        ("Niall Horan", "Heaven", 70),
        ("Calvin Harris", "Miracle", 71),
        ("Megan Thee Stallion", "Cobra", 72),
        ("GloRilla", "Tomorrow 2", 73),
        ("Kali", "Area Codes", 74),
        ("Central Cee", "Let Go", 75),
        ("Rae Sremmurd", "Not So Bad", 76),
        ("Sabrina Carpenter", "Feather", 77),
        ("Tyla", "Truth or Dare", 78),
        ("Peso Pluma", "Bipolar", 79),
        ("Junior H", "El Azul", 80),
        ("Grupo Frontera", "Un x100to", 81),
        ("Bad Bunny", "Monaco", 82),
        ("Drake", "IDGAF", 83),
        ("J Hus", "Who Told You", 84),
        ("Lil Yachty", "Poland", 85),
        ("Jung Kook", "Standing Next to You", 86),
        ("Jung Kook", "3D", 87),
        ("Stray Kids", "Lalalala", 88),
        ("New Jeans", "Super Shy", 89),
        ("Mitski", "My Love Mine All Mine", 90),
    ],
    2024: [
        ("Shaboozey", "A Bar Song", 1),
        ("Teddy Swims", "Lose Control", 2),
        ("Benson Boone", "Beautiful Things", 3),
        ("Sabrina Carpenter", "Espresso", 4),
        ("Kendrick Lamar", "Not Like Us", 5),
        ("Hozier", "Too Sweet", 6),
        ("Post Malone", "I Had Some Help", 7),
        ("Tommy Richman", "Million Dollar Baby", 8),
        ("Billie Eilish", "Birds of a Feather", 9),
        ("Sabrina Carpenter", "Please Please Please", 10),
        ("Chappell Roan", "Good Luck, Babe!", 11),
        ("Taylor Swift", "Fortnight", 12),
        ("Lady Gaga", "Die with a Smile", 13),
        ("Jack Harlow", "Lovin on Me", 14),
        ("Future", "Like That", 15),
        ("Sabrina Carpenter", "Taste", 16),
        ("Morgan Wallen", "I Had Some Help", 17),
        ("Noah Kahan", "Stick Season", 18),
        ("Tate McRae", "Greedy", 19),
        ("Djo", "End of Beginning", 20),
        ("Gracie Abrams", "That's So True", 21),
        ("Eminem", "Houdini", 22),
        ("Beyonce", "Texas Hold 'Em", 23),
        ("Ariana Grande", "We Can't Be Friends", 24),
        ("Rose", "Apt", 25),
        ("Kendrick Lamar", "Like That", 26),
        ("Zach Bryan", "I Remember Everything", 27),
        ("Hozier", "Too Sweet", 28),
        ("Chappell Roan", "Hot to Go", 29),
        ("Benson Boone", "Slow It Down", 30),
        ("Morgan Wallen", "Lies Lies Lies", 31),
        ("Shaboozey", "Good News", 32),
        ("Tinashe", "Nasty", 33),
        ("Megan Thee Stallion", "Hiss", 34),
        ("Doja Cat", "Agora Hills", 35),
        ("Taylor Swift", "I Can Do It with a Broken Heart", 36),
        ("Sabrina Carpenter", "Bed Chem", 37),
        ("Chappell Roan", "Pink Pony Club", 38),
        ("Kendrick Lamar", "Euphoria", 39),
        ("Future", "Type Shit", 40),
        ("Drake", "Family Matters", 41),
        ("Metro Boomin", "Like That", 42),
        ("Tyler the Creator", "Noid", 43),
        ("Gunna", "Fukumean", 44),
        ("Tommy Richman", "Devil Is a Lie", 45),
        ("Flo Milli", "Never Lose Me", 46),
        ("GloRilla", "Yeah Glo", 47),
        ("Cardi B", "Enough Miami", 48),
        ("Sexyy Red", "Get It Sexyy", 49),
        ("Lil Tecca", "500lbs", 50),
        ("Taylor Swift", "Down Bad", 51),
        ("Billie Eilish", "Lunch", 52),
        ("Chappell Roan", "Good Luck Babe", 53),
        ("Ariana Grande", "Yes And", 54),
        ("Dua Lipa", "Houdini", 55),
        ("Charli XCX", "360", 56),
        ("Charli XCX", "Guess", 57),
        ("Sabrina Carpenter", "Nonsense", 58),
        ("Morgan Wallen", "Cowgirls", 59),
        ("Post Malone", "Pour Me a Drink", 60),
        ("Luke Combs", "Where the Wild Things Are", 61),
        ("Jelly Roll", "I Am Not Okay", 62),
        ("Zach Bryan", "Pink Skies", 63),
        ("Kacey Musgraves", "Deeper Well", 64),
        ("Noah Kahan", "Dial Drunk", 65),
        ("Benson Boone", "In the Stars", 66),
        ("Teddy Swims", "The Door", 67),
        ("Tate McRae", "Exes", 68),
        ("Gracie Abrams", "Close to You", 69),
        ("Hozier", "Unknown Nth", 70),
        ("Myles Smith", "Stargazing", 71),
        ("Lola Young", "Messy", 72),
        ("Artemas", "I Like the Way You Kiss Me", 73),
        ("Benson Boone", "Sugar Sweet", 74),
        ("Sophie Ellis-Bextor", "Murder on the Dancefloor", 75),
        ("Tevin Campbell", "Sapphire", 76),
        ("Mark Ambor", "Belong Together", 77),
        ("Le Sserafim", "Easy", 78),
        ("New Jeans", "Supernatural", 79),
        ("Lisa", "Rockstar", 80),
        ("Future", "We Still Don't Trust You", 81),
        ("ScHoolboy Q", "Yeern 101", 82),
        ("21 Savage", "Redrum", 83),
        ("Sexyy Red", "Get It Sexyy", 84),
        ("BossMan Dlow", "Get in with Me", 85),
        ("Cash Cobain", "Fisherrr", 86),
        ("Rich Amiri", "One Call", 87),
        ("4Batz", "Act ii Date at 8", 88),
        ("Muni Long", "Made for Me", 89),
        ("Kehlani", "After Hours", 90),
    ],
    2025: [
        ("Kendrick Lamar", "Luther", 1),
        ("Kendrick Lamar", "Squabble Up", 2),
        ("Lady Gaga", "Die with a Smile", 3),
        ("The Weeknd", "Timeless", 4),
        ("Alex Warren", "Ordinary", 5),
        ("Bad Bunny", "DtMF", 6),
        ("Lady Gaga", "Abracadabra", 7),
        ("Rose", "Apt", 8),
        ("Sabrina Carpenter", "Manchild", 9),
        ("Doechii", "Anxiety", 10),
        ("Morgan Wallen", "I'm the Problem", 11),
        ("Drake", "Nokia", 12),
        ("Billie Eilish", "Birds of a Feather", 13),
        ("Lola Young", "Messy", 14),
        ("Tate McRae", "Sports Car", 15),
        ("Gracie Abrams", "That's So True", 16),
        ("Teddy Swims", "Lose Control", 17),
        ("ROSE", "Number One Girl", 18),
        ("The Weeknd", "Cry for Me", 19),
        ("Morgan Wallen", "Lies Lies Lies", 20),
        ("Post Malone", "Pour Me a Drink", 21),
        ("Mariah The Scientist", "Burning Blue", 22),
        ("Teddy Swims", "Bad Dreams", 23),
        ("Shaboozey", "A Bar Song", 24),
        ("Benson Boone", "Beautiful Things", 25),
        ("Morgan Wallen", "Just in Case", 26),
        ("Kendrick Lamar", "TV Off", 27),
        ("Playboi Carti", "Rather Lie", 28),
        ("Bad Bunny", "Baile Inolvidable", 29),
        ("Bad Bunny", "Nuevayol", 30),
        ("Chappell Roan", "Pink Pony Club", 31),
        ("Chappell Roan", "The Giver", 32),
        ("Sabrina Carpenter", "Espresso", 33),
        ("Selena Gomez", "Sunset Blvd", 34),
        ("Morgan Wallen", "Smile", 35),
        ("Jessie Murph", "Blue Strips", 36),
        ("Hozier", "Too Sweet", 37),
        ("Gigi Perez", "Sailor Song", 38),
        ("Tate McRae", "Just Keep Watching", 39),
        ("Ravyn Lenae", "Love Me Not", 40),
        ("Megan Moroney", "Am I Okay", 41),
        ("Luke Combs", "Ain't No Love in Oklahoma", 42),
        ("Zach Bryan", "Pink Skies", 43),
        ("Morgan Wallen", "Love Somebody", 44),
        ("Wyatt Flores", "Stillhouse", 45),
        ("Jelly Roll", "Liar", 46),
        ("Post Malone", "I Had Some Help", 47),
        ("Shaboozey", "Good News", 48),
        ("Gracie Abrams", "I Love You I'm Sorry", 49),
        ("Lainey Wilson", "4x4xu", 50),
        ("Sombr", "Back to Friends", 51),
        ("Sombr", "Undressed", 52),
        ("Alex Warren", "Bloodline", 53),
        ("Benson Boone", "Sorry I'm Here for Someone Else", 54),
        ("Sabrina Carpenter", "Taste", 55),
        ("Playboi Carti", "Mojo Jojo", 56),
        ("Future", "Like That", 57),
        ("GloRilla", "TGIF", 58),
        ("GloRilla", "Whatchu Kno About Me", 59),
        ("Lil Wayne", "Banned from NO", 60),
        ("Doechii", "Denial Is a River", 61),
        ("SZA", "Saturn", 62),
        ("Kendrick Lamar", "Gloria", 63),
        ("Kendrick Lamar", "Reincarnated", 64),
        ("Bruno Mars", "Die with a Smile", 65),
        ("ROSE", "Toxic Till the End", 66),
        ("Tyla", "Push 2 Start", 67),
        ("Tate McRae", "It's OK I'm OK", 68),
        ("Addison Rae", "Diet Pepsi", 69),
        ("Ariana Grande", "Twilight Zone", 70),
        ("Billie Eilish", "Wildflower", 71),
        ("Lady Gaga", "Disease", 72),
        ("The Weeknd", "São Paulo", 73),
        ("Kali Uchis", "Igual Que un Angel", 74),
        ("Bad Bunny", "Veldá", 75),
        ("Bad Bunny", "Eoo", 76),
        ("Karol G", "Si Antes Te Hubiera Conocido", 77),
        ("Fuerza Regida", "Harley Quinn", 78),
        ("Junior H", "Mi Vida Mi Muerte", 79),
        ("Eslabon Armado", "Lonely Road", 80),
    ],
}


def main(out_path: str = "data/raw/billboard_2016_2025.csv") -> None:
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    rows = []
    for year, songs in YEARS.items():
        for artist, title, rank in songs:
            rows.append({"artist": artist, "title": title, "year": year, "peak": rank})
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["artist", "title", "year", "peak"])
        w.writeheader()
        w.writerows(rows)
    print(f"Wrote {len(rows)} song rows -> {out_path}")
    for year, songs in YEARS.items():
        print(f"  {year}: {len(songs)}")


if __name__ == "__main__":
    main()
