"""Build data/lyrics_full.csv: walkerkq (1964-2015) + Billboard Year-End 2016-2025.

Inputs:
  - data/raw/walkerkq.csv (1964-2015, already lyrics-bearing)
  - data/raw/billboard_2016_2025.csv (artist,title,year,peak) — the 2016-2025
    Year-End Hot 100 list, generated by scripts/build_song_list.py

Lyrics for the 2016-2025 list are fetched lrclib-first (free, key-free JSON API),
falling back to a Genius search only on a miss. lrclib keeps re-runs off the Genius
rate limit and mirrors how lyrics are fetched in src/agent/tools.py.

Output:
  - data/lyrics_full.csv with columns:
      song_id, title, artist, year, decade, chart_position, source, lyrics_raw
"""
import json
import os
import re
import time
import urllib.parse
import urllib.request

import pandas as pd
from dotenv import load_dotenv
import lyricsgenius

load_dotenv()

SONG_LIST_CSV = "data/raw/billboard_2016_2025.csv"


def decade_of(year: int) -> str:
    return f"{(year // 10) * 10}s"


def load_song_list(csv_path: str = SONG_LIST_CSV) -> list[tuple[str, str, int, int]]:
    """Read the Billboard list CSV into (artist, title, year, peak) tuples."""
    df = pd.read_csv(csv_path)
    return [
        (str(r.artist), str(r.title), int(r.year), int(r.peak))
        for r in df.itertuples(index=False)
    ]


def _clean_title(title: str) -> str:
    """Strip featured-artist / remix decorations that break the lrclib track match."""
    t = re.sub(r"\s*[\(\[].*?(feat|ft|with|remix|mixed|version|edit).*?[\)\]]",
               "", title, flags=re.IGNORECASE)
    return t.strip() or title.strip()


def _lrclib_lyrics(artist: str, title: str) -> str | None:
    """Fetch plain lyrics from lrclib.net (free, no-auth JSON API)."""
    qs = urllib.parse.urlencode({"artist_name": artist, "track_name": _clean_title(title)})
    req = urllib.request.Request(
        f"https://lrclib.net/api/get?{qs}",
        headers={"User-Agent": "pop-lyrics-taste-profiler (github.com/wil-li-la)"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            data = json.load(r)
        lyrics = data.get("plainLyrics") or data.get("syncedLyrics")
        return lyrics if lyrics and lyrics.strip() else None
    except Exception:
        return None


def fetch_one(genius: lyricsgenius.Genius | None, artist: str, title: str) -> tuple[str, str] | None:
    """Fetch lyrics, lrclib first then Genius search. Returns (lyrics, source) or None."""
    lyrics = _lrclib_lyrics(artist, title)
    if lyrics:
        return lyrics, "lrclib"
    if genius is not None:
        try:
            song = genius.search_song(title=_clean_title(title), artist=artist,
                                      get_full_info=False)
            if song is not None and song.lyrics:
                return song.lyrics, "genius_api"
        except Exception as e:
            print(f"  [genius ERROR] {artist} - {title}: {e}")
    return None


def load_walkerkq(path: str = "data/raw/walkerkq.csv") -> pd.DataFrame:
    """Load walkerkq dataset into our schema.

    Actual walkerkq columns: Rank, Song, Artist, Year, Lyrics, Source.
    """
    df = pd.read_csv(path, encoding="latin-1")
    df = df.rename(columns={"Rank": "chart_position", "Song": "title",
                            "Artist": "artist", "Year": "year",
                            "Lyrics": "lyrics_raw"})
    df["decade"] = df["year"].apply(decade_of)
    df["source"] = "walkerkq"
    df = df.dropna(subset=["lyrics_raw"])
    df = df[df["lyrics_raw"].str.len() > 100]
    return df[["title", "artist", "year", "decade", "chart_position",
               "source", "lyrics_raw"]]


def scrape_recent(csv_path: str = SONG_LIST_CSV) -> pd.DataFrame:
    """Fetch the Billboard list, lrclib-first with a Genius fallback."""
    song_list = load_song_list(csv_path)
    genius = None
    token = os.environ.get("GENIUS_ACCESS_TOKEN")
    if token:
        genius = lyricsgenius.Genius(
            token, timeout=15, sleep_time=1, remove_section_headers=True,
        )
    rows = []
    n_fail = 0
    src_counts: dict[str, int] = {}
    for i, (artist, title, year, peak) in enumerate(song_list, start=1):
        got = fetch_one(genius, artist, title)
        if got is None:
            print(f"[{i}/{len(song_list)}] {artist} - {title} ({year})  skipped")
            n_fail += 1
            continue
        lyrics, source = got
        src_counts[source] = src_counts.get(source, 0) + 1
        print(f"[{i}/{len(song_list)}] {artist} - {title} ({year})  ok [{source}]")
        rows.append({
            "title": title, "artist": artist, "year": year,
            "decade": decade_of(year), "chart_position": peak,
            "source": source, "lyrics_raw": lyrics,
        })
        time.sleep(0.3)  # polite to lrclib
    print(f"\nScrape: {len(rows)} succeeded / {n_fail} failed "
          f"out of {len(song_list)} ({n_fail / len(song_list):.1%} fail rate)")
    print(f"  by source: {src_counts}")
    return pd.DataFrame(rows)


def merge_and_save(out_path: str = "data/lyrics_full.csv") -> None:
    walkerkq_df = load_walkerkq()
    recent_df = scrape_recent()
    full = pd.concat([walkerkq_df, recent_df], ignore_index=True)
    # Dedupe on lowercased (artist, title)
    full["_key"] = (full["artist"].str.lower().str.strip()
                    + "|" + full["title"].str.lower().str.strip())
    full = full.drop_duplicates(subset="_key", keep="first").drop(columns="_key")
    full = full.reset_index(drop=True)
    full.insert(0, "song_id", [f"S{i:05d}" for i in range(len(full))])
    full.to_csv(out_path, index=False)
    print(f"\nSaved {len(full)} songs -> {out_path}")
    print(full.groupby("decade").size())
    print(full["source"].value_counts())


if __name__ == "__main__":
    merge_and_save()
